// <auto-generated />
using System;
using BurgerShop.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BurgerShop.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260921080938_AddProducts")]
    partial class AddProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BurgerShop.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Burgers"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Nuggets"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fries"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Drinks"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Desserts"
                        });
                });

            modelBuilder.Entity("BurgerShop.API.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BurgerShop.API.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("BurgerShop.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Classic beef burger with lettuce, tomato and sauce.",
                            ImageUrl = "/images/products/ClassicBurger.png",
                            IsAvailable = true,
                            Name = "Classic Burger",
                            Price = 3.00m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Beef burger with cheddar cheese, lettuce, tomato and sauce.",
                            ImageUrl = "/images/products/Cheeseburger.png",
                            IsAvailable = true,
                            Name = "Cheeseburger",
                            Price = 1.20m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Beef burger with cheddar cheese and sauce.",
                            ImageUrl = "/images/products/DoubleCheeseburger.png",
                            IsAvailable = true,
                            Name = "Double Cheeseburger",
                            Price = 2.20m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Classic beef burger with lettuce, tomato and sauce.",
                            ImageUrl = "/images/products/Hamburger.png",
                            IsAvailable = true,
                            Name = "Hamburger",
                            Price = 1.00m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Classic beef burger with lettuce, tomato and sauce.",
                            ImageUrl = "/images/products/BigTeo.png",
                            IsAvailable = true,
                            Name = "Big Teo",
                            Price = 5.00m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Crispy chicken burger with lettuce, tomato and sauce.",
                            ImageUrl = "/images/products/ChickenBurger.jpg",
                            IsAvailable = true,
                            Name = "Chicken Burger",
                            Price = 1.10m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "Crispy bacon burger with lettuce, tomato and sauce.",
                            ImageUrl = "/images/products/CrispyBacon.png",
                            IsAvailable = true,
                            Name = "Crispy Bacon",
                            Price = 4.40m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "Crispy fish burger with lettuce, tomato and sauce.",
                            ImageUrl = "/images/products/FishBurger.png",
                            IsAvailable = true,
                            Name = "Fish Burger",
                            Price = 2.10m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Description = "Crispy bacon burger with lettuce, tomato and sauce.",
                            ImageUrl = "/images/products/DeluxeBurger.png",
                            IsAvailable = true,
                            Name = "Deluxe Burger",
                            Price = 4.80m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Description = "Crispy chicken burger with bacon, lettuce, tomato and sauce.",
                            ImageUrl = "/images/products/ChickenBacon.png",
                            IsAvailable = true,
                            Name = "Chicken Bacon",
                            Price = 4.30m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Description = "Crispy chicken burger with bacon, lettuce, tomato and sauce.",
                            ImageUrl = "/images/products/DoubleChicken.jpg",
                            IsAvailable = true,
                            Name = "Double Chicken",
                            Price = 2.10m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            Description = "Crispy chicken burger with bacon, lettuce, tomato and sauce.",
                            ImageUrl = "/images/products/UncleTeo's.jpg",
                            IsAvailable = true,
                            Name = "Uncle Teo's",
                            Price = 4.00m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            Description = "Crispy chicken burger with bacon, lettuce, tomato and sauce.",
                            ImageUrl = "/images/products/UncleTeo'sSpecial.jpg",
                            IsAvailable = true,
                            Name = "Uncle Teo's Special",
                            Price = 4.50m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            Description = "Crispy chicken burger with lettuce, tomato and sauce.",
                            ImageUrl = "/images/products/JuniorBurger.png",
                            IsAvailable = true,
                            Name = "Junior Burger",
                            Price = 1.10m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Description = "6 crispy chicken nuggets.",
                            ImageUrl = "/images/products/Nuggets6.jpg",
                            IsAvailable = true,
                            Name = "6pc Nuggets",
                            Price = 5.00m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Description = "9 crispy chicken nuggets.",
                            ImageUrl = "/images/products/Nuggets9.jpg",
                            IsAvailable = true,
                            Name = "9pc Nuggets",
                            Price = 7.00m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Description = "20 crispy chicken nuggets.",
                            ImageUrl = "/images/products/Nuggets20.jpg",
                            IsAvailable = true,
                            Name = "20pc Nuggets",
                            Price = 11.00m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            Description = "Crispy golden fries.",
                            ImageUrl = "/images/products/Fries.jpeg",
                            IsAvailable = true,
                            Name = "Small Fries",
                            Price = 1.00m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 3,
                            Description = "Crispy golden fries.",
                            ImageUrl = "/images/products/Fries.jpeg",
                            IsAvailable = true,
                            Name = "Medium Fries",
                            Price = 2.00m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 3,
                            Description = "Crispy golden fries.",
                            ImageUrl = "/images/products/Fries.jpeg",
                            IsAvailable = true,
                            Name = "Large Fries",
                            Price = 3.00m
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 4,
                            Description = "Classic Coca-Cola soft drink.",
                            ImageUrl = "/images/products/Cocacola.jpg",
                            IsAvailable = true,
                            Name = "Coca-Cola",
                            Price = 2.00m
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 4,
                            Description = "Classic Coca-Cola soft drink.",
                            ImageUrl = "/images/products/CocacolaZero.jpg",
                            IsAvailable = true,
                            Name = "Coca-Cola zero",
                            Price = 2.00m
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 4,
                            Description = "Refreshing orange soft drink.",
                            ImageUrl = "/images/products/Fanta.png",
                            IsAvailable = true,
                            Name = "Fanta",
                            Price = 2.00m
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 4,
                            Description = "Refreshing lemon-lime soft drink.",
                            ImageUrl = "/images/products/Sprite.png",
                            IsAvailable = true,
                            Name = "Sprite",
                            Price = 2.00m
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 4,
                            Description = "Filtered water.",
                            ImageUrl = "/images/products/Water.jpg",
                            IsAvailable = true,
                            Name = "Water",
                            Price = 0.50m
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 5,
                            Description = "Delicious vanilla ice cream cone.",
                            ImageUrl = "/images/products/VanillaCone.png",
                            IsAvailable = true,
                            Name = "Vanilla Cone",
                            Price = 1.00m
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 5,
                            Description = "Delicious caramel ice cream cone.",
                            ImageUrl = "/images/products/IceCaramel.png",
                            IsAvailable = true,
                            Name = "Ice Caramel",
                            Price = 1.40m
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 5,
                            Description = "Delicious strawberry ice cream cone.",
                            ImageUrl = "/images/products/IceStrawberry.png",
                            IsAvailable = true,
                            Name = "Ice Strawberry",
                            Price = 1.40m
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 5,
                            Description = "Delicious chocolate ice cream cone.",
                            ImageUrl = "/images/products/IceChocolate.png",
                            IsAvailable = true,
                            Name = "Ice Chocolate",
                            Price = 1.40m
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 5,
                            Description = "Delicious golden ice cream cone.",
                            ImageUrl = "/images/products/IceGolden.jpg",
                            IsAvailable = true,
                            Name = "Ice Golden",
                            Price = 2.00m
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 5,
                            Description = "Delicious vanilla milkshake.",
                            ImageUrl = "/images/products/VanillaMilkshake.jpg",
                            IsAvailable = true,
                            Name = "Vanilla Milkshake",
                            Price = 2.20m
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 5,
                            Description = "Delicious chocolate milkshake.",
                            ImageUrl = "/images/products/ChocolateMilkshake.jpg",
                            IsAvailable = true,
                            Name = "Chocolate Milkshake",
                            Price = 2.20m
                        });
                });

            modelBuilder.Entity("BurgerShop.API.Models.OrderItem", b =>
                {
                    b.HasOne("BurgerShop.API.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BurgerShop.API.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BurgerShop.API.Models.Product", b =>
                {
                    b.HasOne("BurgerShop.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BurgerShop.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BurgerShop.API.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("BurgerShop.API.Models.Product", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
